image: tomcat:7.0-jdk8

services:
  - docker:dind

stages:
  - build
  - package
  - deploy

maven-build:
  image: mcr.microsoft.com/java/maven:8-zulu-debian9
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - combined/target/*.war 

#docker-build:
#  stage: package
#  script:
#  - docker build -t aurimrv/tomcat-img ./web
#  - docker login -u $DOCKER_ID -p $DOCKER_TOKEN
#  - docker push aurimrv/tomcat-img
#  only:
#    - master